# Generated by Django 4.2.7 on 2025-11-24 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('area', models.CharField(max_length=100, verbose_name='Área Forestal')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table': 'checklists',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_visita', models.CharField(max_length=50, unique=True, verbose_name='Código de Visita')),
                ('tipo_visita', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('seguimiento', 'Seguimiento'), ('emergencia', 'Emergencia')], max_length=20, verbose_name='Tipo de Visita')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de Visita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('hallazgos', models.TextField(verbose_name='Hallazgos')),
                ('resultado', models.CharField(choices=[('satisfactorio', 'Satisfactorio'), ('observaciones_menores', 'Observaciones Menores'), ('observaciones_mayores', 'Observaciones Mayores'), ('critico', 'Crítico')], max_length=30, verbose_name='Resultado')),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='seguridad_app.checklist', verbose_name='Checklist Asociado')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_inspeccion', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Visita de Seguridad',
                'verbose_name_plural': 'Visitas de Seguridad',
                'db_table': 'visitas',
                'ordering': ['-fecha_visita', '-hora_inicio'],
            },
        ),
    ]
